name: Release on GitHub

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  release:
    #requires gh cli on the runner: https://github.com/cli/cli/blob/trunk/docs/install_linux.md
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #fetch full history for changelog generation

      - name: Get version from package.json
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "raw_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: tag-check
        run: |
          if git tag -l "${{ steps.package-version.outputs.version }}" | grep -q "${{ steps.package-version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.tag-check.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create "${{ steps.package-version.outputs.version }}" \
            --title "${{ steps.package-version.outputs.version }}" \
            --generate-notes \
            --latest \
            ./src/data/commandData.csv
